[package]
name = "example-service"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
serde_json = "1.0.140"
ssda_types = {path="../ssda_types"}
ssda_client = {path = "../ssda_client"}
tokio = "1.44.2"
mockall = "0.13.1"
tokio-websockets = "0.11.4"
log = "0.4.27"
